#!/usr/bin/env python3
"""Build every page of the site from the files in src/ and content/.

    .venv/bin/python scripts/build.py

  src/layout.html                   the shell shared by every page: <head>, red frame, navbar, footer
  src/pages/*.html                   one file per page (home, about, ...); the front matter says where it goes
  src/project.html                   the layout of a project page, filled in from each project's index.md
  content/site.json                  name, age, navbar links, footer links
  content/projects/<slug>/index.md   one folder per project, with its images: its page and its card on the home page
  content/logos.csv                  the previous-workplaces logo carousel

Write paths from the site root (assets/img/..., about/) everywhere; they are fixed up for each
page's folder. In a project's index.md, an image's bare file name means the file in that
project's folder. Images without width/height get them filled in. Needs Python 3.9+ and the
packages in scripts/requirements.txt, which README.md says how to set up in .venv.
"""
import csv
import datetime
import html
import json
import re
import shutil
import sys
import xml.etree.ElementTree as etree
from pathlib import Path

try:
    import markdown
    import yaml
    from markdown.extensions import Extension
    from markdown.preprocessors import Preprocessor
    from markdown.treeprocessors import Treeprocessor
except ImportError:
    sys.exit("The build needs Markdown and PyYAML. Set up the project's Python once:\n"
             "  python3 -m venv .venv\n  .venv/bin/python -m pip install -r scripts/requirements.txt\n"
             "then run: .venv/bin/python scripts/build.py")

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
CONTENT = ROOT / "content"
PROJECTS = CONTENT / "projects"
WORK = ROOT / "work"
MARKER = "Generated by scripts/build"  # identifies generated pages (also matches the old build_projects.py)

# A project's index.md: the settings its front matter can have, and the sections (# headings) its
# body can have, in the order they appear on the page
SETTINGS = ["title", "description", "order", "tags", "client", "timeline", "team", "goal", "results",
            "card", "hero", "draft", "archived"]
SECTIONS = ["Process", "Final solution", "Extras"]
IMAGE_TYPES = (".avif", ".webp", ".png", ".jpg", ".jpeg", ".gif")
# Videos have YouTube's 854x480 shape; an align-center figure is 60% as wide as an align-full one
VIDEO_PADDING = {"align-full": "56.206088992974244%", "align-center": "33.723653395784545%"}

# Logo carousel: keep in step with .logos-image in site.css
LOGO_GAP = 44      # px between logos (gap and padding-right)
LOGO_SPEED = 99    # px per second, so adding a logo makes the loop longer, not faster
LOGO_HEIGHT = 44   # px, when logos.csv leaves the height empty
TAG_REPEATS = 8    # how many times a card's two tags repeat in its sliding strip


class BuildError(Exception):
    pass


def esc(s):
    return html.escape(str(s), quote=True)


# ---------------------------------------------------------------- templates

def read_template(path):
    """(front matter dict, body) of a template. Front matter is `key: value` lines between --- lines."""
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    meta = {}
    if text.startswith("---\n"):
        head, sep, text = text[4:].partition("\n---\n")
        if not sep:
            raise BuildError("%s: front matter has no closing ---" % path.relative_to(ROOT))
        for line in head.splitlines():
            if line.strip() and not line.lstrip().startswith("#"):
                key, _, value = line.partition(":")
                meta[key.strip()] = value.strip()
    return meta, text


def fill(template, values, where):
    """Replace each {{name}} with values[name]. Inserted text is not scanned again."""
    def sub(m):
        if m.group(1) not in values:
            raise BuildError("%s: unknown placeholder {{%s}}" % (where, m.group(1)))
        return str(values[m.group(1)])
    return re.sub(r"{{\s*(\w+)\s*}}", sub, template)


# ---------------------------------------------------------------- images and paths

def is_local(url):
    return bool(url) and not re.match(r"^([a-zA-Z][a-zA-Z0-9+.-]*:|//|/|#)", url)


def image_size(url):
    """(width, height) of a local AVIF/PNG/GIF/JPEG, or None."""
    if not is_local(url):
        return None
    path = ROOT / html.unescape(url).split("?")[0].split("#")[0]
    if not path.is_file():
        return None
    data = path.read_bytes()
    if data[:8] == b"\x89PNG\r\n\x1a\n":
        return int.from_bytes(data[16:20], "big"), int.from_bytes(data[20:24], "big")
    if data[:6] in (b"GIF87a", b"GIF89a"):
        return int.from_bytes(data[6:8], "little"), int.from_bytes(data[8:10], "little")
    if b"ftypavif" in data[:32] or b"ftypavis" in data[:32]:
        # Large AVIFs can be stored as a grid of tiles, each with its own size; the full image is the largest
        sizes = [(int.from_bytes(data[m.start() + 8:m.start() + 12], "big"), int.from_bytes(data[m.start() + 12:m.start() + 16], "big"))
                 for m in re.finditer(b"ispe", data[:65536])]
        if sizes:
            return max(sizes, key=lambda s: s[0] * s[1])
    if data[:2] == b"\xff\xd8":
        i = 2
        while i < len(data) - 9:
            marker, seglen = data[i + 1], int.from_bytes(data[i + 2:i + 4], "big")
            if marker in (0xC0, 0xC1, 0xC2):
                return int.from_bytes(data[i + 7:i + 9], "big"), int.from_bytes(data[i + 5:i + 7], "big")
            i += 2 + seglen
    return None


def dims(url):
    size = image_size(url)
    return ' width="%d" height="%d"' % size if size else ""


def add_image_sizes(page):
    """Give every local <img> without a width and height its file's size, so the page doesn't jump as images load."""
    def img(m):
        tag = m.group(0)
        if re.search(r"\s(width|height)=", tag):
            return tag
        src = re.search(r'(\ssrc="([^"]*)")', tag)
        return tag.replace(src.group(1), src.group(1) + dims(src.group(2)), 1) if src else tag
    return re.sub(r"<img\b[^>]*>", img, page)


def relink(page, root):
    """Point site-root paths (assets/..., about/) at the right place from a page `root` folders deep."""
    def fix(url):
        if url == "./":
            return root or "./"
        return root + url if is_local(url) else url

    def attr(m):
        name, value = m.group(1), m.group(2)
        if name == "srcset":
            value = ", ".join(fix(part.strip().split(" ", 1)[0]) + (" " + part.strip().split(" ", 1)[1] if " " in part.strip() else "")
                              for part in value.split(","))
        else:
            value = fix(value)
        return ' %s="%s"' % (name, value)
    return re.sub(r'\s(src|href|srcset|poster)="([^"]*)"', attr, page)


# ---------------------------------------------------------------- content

def load_site():
    site = json.loads((CONTENT / "site.json").read_text(encoding="utf-8"))
    site["year"] = datetime.date.today().year
    return site


def load_projects():
    """Published projects from content/projects/<slug>/index.md, in `order`. Folders starting with _ are skipped."""
    folders = [d for d in sorted(PROJECTS.iterdir()) if d.is_dir() and not d.name.startswith(("_", "."))] if PROJECTS.is_dir() else []
    projects = [p for p in map(read_project, folders) if p]
    projects.sort(key=lambda p: (p["order"] if p["order"] is not None else 10 ** 6, p["slug"]))
    return projects


def read_project(folder):
    """A project's settings, and its sections as HTML, from <folder>/index.md. None for a draft or an archived one."""
    slug, rel = folder.name, folder.relative_to(ROOT).as_posix()
    where = rel + "/index.md"
    if not (folder / "index.md").is_file():
        raise BuildError('%s/ has no index.md. To start a project, run: .venv/bin/python scripts/new_project.py "Project name"' % rel)
    if not re.match(r"^[a-z0-9]+(-[a-z0-9]+)*$", slug):
        raise BuildError("%s/: the folder's name is the page's address, so it should be lowercase words joined by hyphens, like my-project" % rel)
    text = (folder / "index.md").read_text(encoding="utf-8-sig").replace("\r\n", "\n")
    front = re.match(r"---\n(.*?\n)?---[ \t]*(\n|$)", text, re.S)
    if not front:
        raise BuildError("%s: should start with its settings, between two --- lines" % where)
    try:
        # BaseLoader keeps every value as written (YAML would otherwise turn 010 into 8, and No into False)
        meta = yaml.load(front.group(1) or "", Loader=yaml.BaseLoader) or {}
    except yaml.YAMLError as e:
        mark = getattr(e, "problem_mark", None)
        raise BuildError('%s%s: can\'t read the settings (%s). If a value contains ": " or " #", put it in "double quotes".'
                         % (where, ", line %d" % (mark.line + 2) if mark else "", getattr(e, "problem", None) or e))
    if not isinstance(meta, dict):
        raise BuildError("%s: the settings should be `name: value` lines" % where)
    unknown = [k for k in meta if k not in SETTINGS]
    if unknown:
        raise BuildError("%s: there's no setting called %s. The settings are %s." % (where, " or ".join("`%s`" % k for k in unknown), ", ".join(SETTINGS)))

    def setting(key, required=False):
        value = meta.get(key, "")
        if not isinstance(value, str):
            raise BuildError("%s: `%s:` should be text" % (where, key))
        if required and not value.strip():
            raise BuildError("%s: `%s:` is missing" % (where, key))
        return value.strip()

    def flag(key):
        value = setting(key).lower()
        if value not in ("", "true", "false"):
            raise BuildError("%s: `%s:` should be true or false" % (where, key))
        return value == "true"

    def image(key):
        """The card or hero image: the one set in the settings, or else card.* or hero.* in the folder."""
        name = setting(key) or next((f.name for f in sorted(folder.iterdir()) if f.stem == key and f.suffix.lower() in IMAGE_TYPES), "")
        if not name:
            raise BuildError("%s: there's no %s image. Put it in the folder as %s.png, .jpg or .avif, or set `%s:` to its file name." % (where, key, key, key))
        return project_image(slug, name)

    if flag("draft") or flag("archived"):
        return None
    order, tags, results = setting("order"), meta.get("tags"), meta.get("results") or []
    if order and not order.isdigit():
        raise BuildError("%s: `order:` should be a number, like 3" % where)
    if not (isinstance(tags, list) and len(tags) == 2 and all(isinstance(t, str) and t.strip() for t in tags)):
        raise BuildError("%s: `tags:` should be two tags, like [Product Design, Content Discovery]" % where)
    if not (isinstance(results, list) and len(results) in (0, 3)
            and all(isinstance(r, list) and len(r) == 2 and all(isinstance(s, str) for s in r) for r in results)):
        raise BuildError("%s: `results:` should be three lines like - [80%%, flow completion rate], or left out" % where)
    return {
        "slug": slug, "source": where, "order": int(order) if order else None,
        "title": setting("title", True), "description": setting("description", True),
        "tags": [t.strip() for t in tags], "card": image("card"), "hero": image("hero"),
        "client": setting("client"), "timeline": setting("timeline"), "team": setting("team"), "goal": setting("goal"),
        "results": [(value.strip(), label.strip()) for value, label in results],
        "sections": read_sections(text[front.end():], slug, where),
    }


def project_image(slug, name):
    """The site-root path of an image named in a project's index.md: a bare file name is in the project's folder."""
    return "content/projects/%s/%s" % (slug, name) if is_local(name) and "/" not in name else name


def read_sections(body, slug, where):
    """[(label, html)] for the # Process, # Final solution and # Extras sections of a project's index.md.
    A section that's missing or empty isn't shown."""
    body = re.sub(r"<!--.*?-->", "", body, flags=re.S)  # notes to yourself
    parts = re.split(r"^#(?!#)[ \t]*(.*?)[ \t#]*$", body, flags=re.M)
    if parts[0].strip():
        raise BuildError("%s: the text above the first section isn't shown. Put it under # Process, # Final solution or # Extras." % where)
    sections, seen = [], []
    for heading, text in zip(parts[1::2], parts[2::2]):
        label = next((s for s in SECTIONS if s.lower() == heading.lower()), None)
        if not label:
            raise BuildError('%s: "# %s" isn\'t a section. The sections are # Process, # Final solution and # Extras; '
                             'use ## for headings inside them.' % (where, heading))
        if seen and SECTIONS.index(label) <= SECTIONS.index(seen[-1]):
            raise BuildError("%s: each section can appear once, in this order: # Process, # Final solution, # Extras" % where)
        seen.append(label)
        rendered = markdown.markdown(text, extensions=["attr_list", "md_in_html", ProjectMarkdown()])
        rendered = re.sub(r'(<img\b[^>]*?\ssrc=")([^"]*)"', lambda m: '%s%s"' % (m.group(1), project_image(slug, m.group(2))), rendered)
        if rendered.strip():
            sections.append((label, rendered))
    return sections


class ProjectMarkdown(Extension):
    """What project pages add to Markdown: a YouTube link alone on its line becomes a video, an image
    alone in its paragraph becomes a figure ({.center} after either makes it narrower), and headings
    move up a level (## is <h1>, ### is <h2>), since # starts a section."""

    def extendMarkdown(self, md):
        md.preprocessors.register(YouTubeLines(md), "youtube", 15)  # after raw HTML has been set aside (20)
        md.treeprocessors.register(Figures(md), "figures", 5)       # after attr_list has read {.center} (8)
        md.treeprocessors.deregister("prettify")  # no line breaks between blocks, so existing HTML comes out exactly as written


# https://www.youtube.com/watch?v=<id> or https://youtu.be/<id>, then optionally "Title" and {.center}
YOUTUBE = re.compile(r'https?://(?:www\.|m\.)?(?:youtube\.com/(?:watch\?(?:[^\s"{]*&)?v=|embed/|shorts/)|youtu\.be/)'
                     r'([A-Za-z0-9_-]{11})[^\s"{]*(?:[ \t]+"([^"]*)")?[ \t]*(\{:?[ \t]*\.center[ \t]*\})?[ \t]*')
CENTER = re.compile(r"\s*(\{:?\s*\.center\s*\})?\s*")  # what may follow an image: {.center}, also with a space before it


class YouTubeLines(Preprocessor):
    def run(self, lines):
        out = []
        for line in lines:
            m = YOUTUBE.fullmatch(line)
            if not m:
                out.append(line)
                continue
            align = "align-center" if m.group(3) else "align-full"
            out += ["", self.md.htmlStash.store(
                '<figure class="figure-video %s" style="padding-bottom:%s"><div><iframe src="https://www.youtube.com/embed/%s" '
                'title="%s" allowfullscreen></iframe></div></figure>' % (align, VIDEO_PADDING[align], m.group(1), esc(m.group(2) or "YouTube video"))), ""]
        return out


class Figures(Treeprocessor):
    def run(self, root):
        for parent in list(root.iter()):
            for i, p in enumerate(list(parent)):
                if p.tag != "p" or len(p) != 1 or p[0].tag != "img" or (p.text or "").strip():
                    continue
                center = CENTER.fullmatch(p[0].tail or "")
                if not center:
                    continue
                img = p[0]
                classes = img.attrib.pop("class", "").split()
                img.tail = None
                figure = etree.Element("figure", {"class": "figure-image " + ("align-center" if center.group(1) or "center" in classes else "align-full")})
                etree.SubElement(figure, "div").append(img)
                figure.tail = p.tail
                parent[i] = figure
        for el in root.iter():
            if isinstance(el.tag, str) and re.fullmatch(r"h[2-6]", el.tag):
                el.tag = "h%d" % (int(el.tag[1]) - 1)


def load_logos():
    with open(CONTENT / "logos.csv", encoding="utf-8-sig", newline="") as f:
        return [r for r in csv.DictReader(f) if (r.get("file") or "").strip()]


# ---------------------------------------------------------------- shared pieces

def render_nav(site, current):
    links = []
    for item in site["nav"]:
        if item.get("page") and item["page"] == current:
            links.append('<a href="#top" aria-current="page" class="navbar-control-link active" id="homeLink">%s</a>' % esc(item["label"]))
        elif is_local(item["href"]) or item["href"] == "./":
            links.append('<a href="%s" class="navbar-control-link">%s</a>' % (esc(item["href"]), esc(item["label"])))
        else:
            links.append('<a href="%s" target="_blank" rel="noopener" class="navbar-control-link">%s</a>' % (esc(item["href"]), esc(item["label"])))
    return "\n".join("      " + a for a in links)


def bracket(bottom):
    b = " bottom" if bottom else ""
    return ('<div class="footer-action-bracket%s" aria-hidden="true"><span class="bracket-edge%s"></span>'
            '<span class="footer-edge-base%s"></span><span class="bracket-edge right%s"></span></div>') % (b, b, b, b)


def render_footer_links(site):
    rows = []
    for row in site["links"]:
        mail = row[0]["href"].startswith("mailto:")
        links = "".join(
            '<a class="footer-action" href="%s"%s>%s<div class="footer-action-title-container"><h1 class="footer-action-title">%s</h1>'
            '<div class="footer-action-underline-container"><div class="footer-action-underline"></div></div></div>%s'
            '<p class="footer-action-subtitle">%s</p></a>' % (
                esc(link["href"]), "" if link["href"].startswith("mailto:") else ' target="_blank" rel="noopener"',
                bracket(False), esc(link["title"]), bracket(True), esc(link["subtitle"]))
            for link in row)
        rows.append('    <div class="footer-actions-row%s">%s</div>' % (" mailing" if mail else "", links))
    return "\n".join(rows)


def render_cards(projects):
    def strip(p):
        return "".join("<p>%s</p><p>*</p><p>%s</p><p>*</p>" % (esc(p["tags"][0]), esc(p["tags"][1])) for _ in range(TAG_REPEATS))

    cards = []
    for p in projects:
        cards.append(
            '<div class="project-container" role="listitem"><a class="project-link-container" href="work/%s/">'
            '<div class="project-attributes-container top" aria-hidden="true"><div class="project-attributes-list">%s</div></div>'
            '<div class="project-content-and-image"><div class="project-title-and-subtitle"><h2>%s</h2><p class="project-description">%s</p>'
            '<span class="sr-only">%s, %s</span></div>'
            '<div class="image-container project"><img class="image-slot" src="%s" alt=""></div></div>'
            '<div class="project-attributes-container bottom" aria-hidden="true"><div class="project-attributes-list">%s</div></div>'
            '</a></div>' % (
                p["slug"], strip(p), esc(p["title"]), esc(p["description"]), esc(p["tags"][0]), esc(p["tags"][1]),
                esc(p["card"]), strip(p)))
    return "\n".join("          " + c for c in cards)


def render_logos(logos):
    """Both copies of the logo row, and how long one loop takes at LOGO_SPEED."""
    imgs, copies, row_width = [], [], 0
    for logo in logos:
        src = "assets/img/logos/" + logo["file"].strip()
        size = image_size(src)
        if not size:
            raise BuildError("content/logos.csv: can't read %s" % src)
        height = float(logo.get("height") or LOGO_HEIGHT)
        row_width += height * size[0] / size[1] + LOGO_GAP
        imgs.append((src, logo["name"].strip(), size, "%gpx" % height))
    for hidden in (False, True):
        copies.append('<div class="logos-image"%s>%s</div>' % (' aria-hidden="true"' if hidden else "", "".join(
            '<img class="logo" src="%s" alt="%s" width="%d" height="%d" style="--h:%s" loading="lazy" decoding="async">'
            % (esc(src), "" if hidden else esc(name), w, h, height) for src, name, (w, h), height in imgs)))
    return "\n".join("          " + c for c in copies), "%.1fs" % (row_width / LOGO_SPEED)


# ---------------------------------------------------------------- project pages

def prepare_rich_text(src):
    """A section's HTML, with images and embeds set to load lazily."""
    def img(m):
        tag = m.group(0)
        s = html.unescape(re.search(r'\ssrc="([^"]*)"', tag).group(1))
        alt = re.search(r'\salt="([^"]*)"', tag)
        return '<img src="%s"%s loading="lazy" decoding="async" alt="%s">' % (s.replace('"', "&quot;"), dims(s), alt.group(1) if alt else "")
    h = re.sub(r"<img\b[^>]*>", img, src)
    h = re.sub(r"<iframe\b", '<iframe loading="lazy"', h)
    h = re.sub(r'(<a\b[^>]*target="_blank")', r'\1 rel="noopener"', h)
    return h


def section(label, body):
    return ('  <div class="project-content-container">\n'
            '    <p class="wavy-underline section-label">%s</p><p>&nbsp;</p>\n'
            '    <div class="rich-text">%s</div>\n'
            '  </div>\n') % (label, prepare_rich_text(body))


def metric(value, label):
    return ('    <div class="project-metric">'
            '<div class="testimonial-top-content"><div class="testimonial-top-left"></div>'
            '<img class="testimonial-top-right-fold" src="assets/img/ui/card-fold.png" alt=""></div>'
            '<div class="testimonial-bottom-content project-metric-body">'
            '<h2>%s</h2><p>%s</p></div></div>\n') % (esc(value), esc(label))


def project_values(p):
    results = p["results"]
    return {
        "title": esc(p["title"]), "description": esc(p["description"]), "hero": esc(p["hero"]),
        "client": esc(p["client"]), "timeline": esc(p["timeline"]), "team": esc(p["team"]), "goal": esc(p["goal"]),
        "results_label": '    <p>&nbsp;</p><p>&nbsp;</p><p class="wavy-underline section-label">Results</p>\n' if results else "",
        "results": ('  <div class="project-content-container results">\n%s  </div>\n'
                    % "".join(metric(value, label) for value, label in results)) if results else "",
        "sections": "".join(section(label, body) for label, body in p["sections"]),
    }


# ---------------------------------------------------------------- pages

def render_page(site, layout, meta, content, output, source):
    """A full page: `content` inside the shared layout, written to `output` (relative to the site root)."""
    depth = output.count("/")
    root = "../" * depth
    page_path = re.sub(r"index\.html$", "", output)
    og_image = meta.get("og_image") or site["og_image"]
    og_size = image_size(og_image)
    values = {
        "generated": "%s.py from %s. Edit that, not this file." % (MARKER, source),
        "site_name": esc(site["name"]),
        "title": esc(meta["title"]),
        "og_title": esc(meta.get("og_title") or meta["title"]),
        "description": esc(meta.get("description") or site["description"]),
        "url": esc(site["url"] + page_path),
        "og_image": esc(site["url"] + og_image if is_local(og_image) else og_image),
        "og_image_size": ('<meta property="og:image:width" content="%d">\n<meta property="og:image:height" content="%d">\n' % og_size) if og_size else "",
        "og_image_alt": esc(meta.get("og_image_alt") or site["og_image_alt"]),
        "nav_links": render_nav(site, meta.get("nav")),
        "main_class": esc(meta.get("main_class") or "page-container"),
        "content": content.rstrip("\n"),
        "footer_links": render_footer_links(site),
        "year": site["year"],
        "secret": esc(meta.get("secret", "")),
        "script": esc(meta.get("script") or "about.js"),
    }
    page = fill(layout, values, "src/layout.html")
    page = relink(add_image_sizes(page), root)
    path = ROOT / output
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(page)
    print("built", output)
    return page_path


def build():
    site = load_site()
    projects = load_projects()
    logos, logos_duration = render_logos(load_logos())
    _, layout = read_template(SRC / "layout.html")
    shared = {
        "age": esc(site["age"]), "year": site["year"],
        "projects": render_cards(projects), "project_count": len(projects),
        "logos": logos, "logos_duration": logos_duration,
    }
    urls = []

    for source in sorted((SRC / "pages").glob("*.html")):
        meta, body = read_template(source)
        rel = source.relative_to(ROOT).as_posix()
        for key in ("output", "title"):
            if not meta.get(key):
                raise BuildError("%s: front matter needs `%s:`" % (rel, key))
        urls.append(render_page(site, layout, meta, fill(body, shared, rel), meta["output"], rel))

    # Project pages, and removing pages of projects that were deleted, archived or set to draft
    meta, body = read_template(SRC / "project.html")
    keep = {p["slug"] for p in projects}
    if WORK.exists():
        for d in sorted(WORK.iterdir()):
            page = d / "index.html"
            if d.is_dir() and d.name not in keep and page.exists() and MARKER in page.read_text(encoding="utf-8"):
                shutil.rmtree(d)
                print("removed", d.relative_to(ROOT).as_posix())
    for p in projects:
        og = "content/projects/%s/og.jpg" % p["slug"]
        page_meta = dict(meta, title=p["title"] + " – " + site["name"], og_title=p["title"], description=p["description"],
                         og_image_alt=p["title"], **({"og_image": og} if (ROOT / og).exists() else {}))
        content = fill(body, project_values(p), "src/project.html")
        urls.append(render_page(site, layout, page_meta, content, "work/%s/index.html" % p["slug"], p["source"]))

    write_sitemap(site, urls)


def write_sitemap(site, paths):
    """sitemap.xml: home first, then the other pages, then projects."""
    paths = sorted(paths, key=lambda p: (p != "", p.startswith("work/"), paths.index(p)))
    body = "\n".join("  <url><loc>%s</loc></url>" % esc(site["url"] + p) for p in paths)
    with open(ROOT / "sitemap.xml", "w", encoding="utf-8", newline="\n") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n'
                '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n%s\n</urlset>\n' % body)
    print("built sitemap.xml")


def main():
    try:
        build()
    except BuildError as e:
        raise SystemExit("error: %s" % e)


if __name__ == "__main__":
    main()
