#!/usr/bin/env python3
"""Build every page of the site from the files in src/ and content/.

    python3 scripts/build.py

  src/layout.html         the shell shared by every page: <head>, red frame, navbar, footer
  src/pages/*.html        one file per page (home, about, ...); the front matter says where it goes
  src/project.html        the layout of a project page, filled in from each row of the CSV
  content/site.json       name, age, navbar links, footer links
  content/projects.csv    one row per project: its page and its card on the home page
  content/logos.csv       the previous-workplaces logo carousel

Write paths from the site root (assets/img/..., about/) everywhere; they are fixed up for each
page's folder. Images without width/height get them filled in. Only the Python standard library
is used, so this runs anywhere Python 3.9+ does.
"""
import csv
import datetime
import html
import json
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
CONTENT = ROOT / "content"
WORK = ROOT / "work"
MARKER = "Generated by scripts/build"  # identifies generated pages (also matches the old build_projects.py)

# Logo carousel: keep in step with .logos-image in site.css
LOGO_GAP = 44      # px between logos (gap and padding-right)
LOGO_SPEED = 99    # px per second, so adding a logo makes the loop longer, not faster
LOGO_HEIGHT = 44   # px, when logos.csv leaves the height empty
TAG_REPEATS = 8    # how many times a card's two tags repeat in its sliding strip


class BuildError(Exception):
    pass


def esc(s):
    return html.escape(str(s), quote=True)


def truthy(v):
    return (v or "").strip().lower() == "true"


# ---------------------------------------------------------------- templates

def read_template(path):
    """(front matter dict, body) of a template. Front matter is `key: value` lines between --- lines."""
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    meta = {}
    if text.startswith("---\n"):
        head, sep, text = text[4:].partition("\n---\n")
        if not sep:
            raise BuildError("%s: front matter has no closing ---" % path.relative_to(ROOT))
        for line in head.splitlines():
            if line.strip() and not line.lstrip().startswith("#"):
                key, _, value = line.partition(":")
                meta[key.strip()] = value.strip()
    return meta, text


def fill(template, values, where):
    """Replace each {{name}} with values[name]. Inserted text is not scanned again."""
    def sub(m):
        if m.group(1) not in values:
            raise BuildError("%s: unknown placeholder {{%s}}" % (where, m.group(1)))
        return str(values[m.group(1)])
    return re.sub(r"{{\s*(\w+)\s*}}", sub, template)


# ---------------------------------------------------------------- images and paths

def is_local(url):
    return bool(url) and not re.match(r"^([a-zA-Z][a-zA-Z0-9+.-]*:|//|/|#)", url)


def image_size(url):
    """(width, height) of a local AVIF/PNG/GIF/JPEG, or None."""
    if not is_local(url):
        return None
    path = ROOT / html.unescape(url).split("?")[0].split("#")[0]
    if not path.is_file():
        return None
    data = path.read_bytes()
    if data[:8] == b"\x89PNG\r\n\x1a\n":
        return int.from_bytes(data[16:20], "big"), int.from_bytes(data[20:24], "big")
    if data[:6] in (b"GIF87a", b"GIF89a"):
        return int.from_bytes(data[6:8], "little"), int.from_bytes(data[8:10], "little")
    if b"ftypavif" in data[:32] or b"ftypavis" in data[:32]:
        # Large AVIFs can be stored as a grid of tiles, each with its own size; the full image is the largest
        sizes = [(int.from_bytes(data[m.start() + 8:m.start() + 12], "big"), int.from_bytes(data[m.start() + 12:m.start() + 16], "big"))
                 for m in re.finditer(b"ispe", data[:65536])]
        if sizes:
            return max(sizes, key=lambda s: s[0] * s[1])
    if data[:2] == b"\xff\xd8":
        i = 2
        while i < len(data) - 9:
            marker, seglen = data[i + 1], int.from_bytes(data[i + 2:i + 4], "big")
            if marker in (0xC0, 0xC1, 0xC2):
                return int.from_bytes(data[i + 7:i + 9], "big"), int.from_bytes(data[i + 5:i + 7], "big")
            i += 2 + seglen
    return None


def dims(url):
    size = image_size(url)
    return ' width="%d" height="%d"' % size if size else ""


def add_image_sizes(page):
    """Give every local <img> without a width and height its file's size, so the page doesn't jump as images load."""
    def img(m):
        tag = m.group(0)
        if re.search(r"\s(width|height)=", tag):
            return tag
        src = re.search(r'(\ssrc="([^"]*)")', tag)
        return tag.replace(src.group(1), src.group(1) + dims(src.group(2)), 1) if src else tag
    return re.sub(r"<img\b[^>]*>", img, page)


def relink(page, root):
    """Point site-root paths (assets/..., about/) at the right place from a page `root` folders deep."""
    def fix(url):
        if url == "./":
            return root or "./"
        return root + url if is_local(url) else url

    def attr(m):
        name, value = m.group(1), m.group(2)
        if name == "srcset":
            value = ", ".join(fix(part.strip().split(" ", 1)[0]) + (" " + part.strip().split(" ", 1)[1] if " " in part.strip() else "")
                              for part in value.split(","))
        else:
            value = fix(value)
        return ' %s="%s"' % (name, value)
    return re.sub(r'\s(src|href|srcset|poster)="([^"]*)"', attr, page)


# ---------------------------------------------------------------- content

def load_site():
    site = json.loads((CONTENT / "site.json").read_text(encoding="utf-8"))
    site["year"] = datetime.date.today().year
    return site


def load_projects():
    """Published projects from content/projects.csv, in `order`."""
    with open(CONTENT / "projects.csv", encoding="utf-8-sig", newline="") as f:
        rows = [r for r in csv.DictReader(f) if not truthy(r["Archived"]) and not truthy(r["Draft"])]
    required = ["Slug", "Heading", "description", "home-thumbnail", "attribute-1", "attribute-2", "full-thumbnail"]
    seen = set()
    for r in rows:
        missing = [c for c in required if not (r.get(c) or "").strip()]
        if missing:
            raise BuildError("content/projects.csv: %r is missing %s" % (r.get("Name") or r.get("Slug"), ", ".join(missing)))
        if not re.match(r"^[a-z0-9]+(-[a-z0-9]+)*$", r["Slug"]):
            raise BuildError("content/projects.csv: Slug %r should be lowercase words joined by hyphens, like my-project" % r["Slug"])
        if r["Slug"] in seen:
            raise BuildError("content/projects.csv: two projects use the Slug %r" % r["Slug"])
        seen.add(r["Slug"])
    rows.sort(key=lambda r: (int(r["order"]) if r["order"].strip() else 10 ** 6, r["Slug"]))
    return rows


def load_logos():
    with open(CONTENT / "logos.csv", encoding="utf-8-sig", newline="") as f:
        return [r for r in csv.DictReader(f) if (r.get("file") or "").strip()]


# ---------------------------------------------------------------- shared pieces

def render_nav(site, current):
    links = []
    for item in site["nav"]:
        if item.get("page") and item["page"] == current:
            links.append('<a href="#top" aria-current="page" class="navbar-control-link active" id="homeLink">%s</a>' % esc(item["label"]))
        elif is_local(item["href"]) or item["href"] == "./":
            links.append('<a href="%s" class="navbar-control-link">%s</a>' % (esc(item["href"]), esc(item["label"])))
        else:
            links.append('<a href="%s" target="_blank" rel="noopener" class="navbar-control-link">%s</a>' % (esc(item["href"]), esc(item["label"])))
    return "\n".join("      " + a for a in links)


def bracket(bottom):
    b = " bottom" if bottom else ""
    return ('<div class="footer-action-bracket%s" aria-hidden="true"><span class="bracket-edge%s"></span>'
            '<span class="footer-edge-base%s"></span><span class="bracket-edge right%s"></span></div>') % (b, b, b, b)


def render_footer_links(site):
    rows = []
    for row in site["links"]:
        mail = row[0]["href"].startswith("mailto:")
        links = "".join(
            '<a class="footer-action" href="%s"%s>%s<div class="footer-action-title-container"><h1 class="footer-action-title">%s</h1>'
            '<div class="footer-action-underline-container"><div class="footer-action-underline"></div></div></div>%s'
            '<p class="footer-action-subtitle">%s</p></a>' % (
                esc(link["href"]), "" if link["href"].startswith("mailto:") else ' target="_blank" rel="noopener"',
                bracket(False), esc(link["title"]), bracket(True), esc(link["subtitle"]))
            for link in row)
        rows.append('    <div class="footer-actions-row%s">%s</div>' % (" mailing" if mail else "", links))
    return "\n".join(rows)


def render_cards(projects):
    def strip(p):
        return "".join("<p>%s</p><p>*</p><p>%s</p><p>*</p>" % (esc(p["attribute-1"]), esc(p["attribute-2"])) for _ in range(TAG_REPEATS))

    cards = []
    for p in projects:
        cards.append(
            '<div class="project-container" role="listitem"><a class="project-link-container" href="work/%s/">'
            '<div class="project-attributes-container top" aria-hidden="true"><div class="project-attributes-list">%s</div></div>'
            '<div class="project-content-and-image"><div class="project-title-and-subtitle"><h2>%s</h2><p class="project-description">%s</p>'
            '<span class="sr-only">%s, %s</span></div>'
            '<div class="image-container project"><img class="image-slot" src="%s" alt=""></div></div>'
            '<div class="project-attributes-container bottom" aria-hidden="true"><div class="project-attributes-list">%s</div></div>'
            '</a></div>' % (
                p["Slug"], strip(p), esc(p["Heading"]), esc(p["description"]), esc(p["attribute-1"]), esc(p["attribute-2"]),
                esc(p["home-thumbnail"]), strip(p)))
    return "\n".join("          " + c for c in cards)


def render_logos(logos):
    """Both copies of the logo row, and how long one loop takes at LOGO_SPEED."""
    imgs, copies, row_width = [], [], 0
    for logo in logos:
        src = "assets/img/logos/" + logo["file"].strip()
        size = image_size(src)
        if not size:
            raise BuildError("content/logos.csv: can't read %s" % src)
        height = float(logo.get("height") or LOGO_HEIGHT)
        row_width += height * size[0] / size[1] + LOGO_GAP
        imgs.append((src, logo["name"].strip(), size, "%gpx" % height))
    for hidden in (False, True):
        copies.append('<div class="logos-image"%s>%s</div>' % (' aria-hidden="true"' if hidden else "", "".join(
            '<img class="logo" src="%s" alt="%s" width="%d" height="%d" style="--h:%s" loading="lazy" decoding="async">'
            % (esc(src), "" if hidden else esc(name), w, h, height) for src, name, (w, h), height in imgs)))
    return "\n".join("          " + c for c in copies), "%.1fs" % (row_width / LOGO_SPEED)


# ---------------------------------------------------------------- project pages

def prepare_rich_text(src):
    """Rich text from the CSV, with images and embeds set to load lazily."""
    def img(m):
        tag = m.group(0)
        s = html.unescape(re.search(r'\ssrc="([^"]*)"', tag).group(1))
        alt = re.search(r'\salt="([^"]*)"', tag)
        return '<img src="%s"%s loading="lazy" decoding="async" alt="%s">' % (s.replace('"', "&quot;"), dims(s), alt.group(1) if alt else "")
    h = re.sub(r"<img\b[^>]*>", img, src)
    h = re.sub(r"<iframe\b", '<iframe loading="lazy"', h)
    h = re.sub(r'(<a\b[^>]*target="_blank")', r'\1 rel="noopener"', h)
    return h


def section(label, body):
    return ('  <div class="project-content-container">\n'
            '    <p class="wavy-underline section-label">%s</p><p>&nbsp;</p>\n'
            '    <div class="rich-text">%s</div>\n'
            '  </div>\n') % (label, prepare_rich_text(body))


def metric(value, label):
    return ('    <div class="project-metric">'
            '<div class="testimonial-top-content"><div class="testimonial-top-left"></div>'
            '<img class="testimonial-top-right-fold" src="assets/img/ui/card-fold.png" alt=""></div>'
            '<div class="testimonial-bottom-content project-metric-body">'
            '<h2>%s</h2><p>%s</p></div></div>\n') % (esc(value), esc(label))


def project_values(p):
    results = truthy(p["results-applicable"])
    sections = ""
    for key, label in (("research", "Process"), ("final-solution", "Final solution"), ("extras", "Extras")):
        if truthy(p[key + "-applicable"]):
            sections += section(label, p[key])
    return {
        "heading": esc(p["Heading"]), "description": esc(p["description"]), "hero": esc(p["full-thumbnail"]),
        "org": esc(p["org"]), "timeline": esc(p["timeline"]), "team": esc(p["team"]), "goal": esc(p["goal"]),
        "results_label": '    <p>&nbsp;</p><p>&nbsp;</p><p class="wavy-underline section-label">Results</p>\n' if results else "",
        "results": ('  <div class="project-content-container results">\n%s  </div>\n'
                    % "".join(metric(p["m%d-heading" % i], p["m%d-desc" % i]) for i in (1, 2, 3))) if results else "",
        "sections": sections,
    }


# ---------------------------------------------------------------- pages

def render_page(site, layout, meta, content, output, source):
    """A full page: `content` inside the shared layout, written to `output` (relative to the site root)."""
    depth = output.count("/")
    root = "../" * depth
    page_path = re.sub(r"index\.html$", "", output)
    og_image = meta.get("og_image") or site["og_image"]
    og_size = image_size(og_image)
    values = {
        "generated": "%s.py from %s. Edit that, not this file." % (MARKER, source),
        "site_name": esc(site["name"]),
        "title": esc(meta["title"]),
        "og_title": esc(meta.get("og_title") or meta["title"]),
        "description": esc(meta.get("description") or site["description"]),
        "url": esc(site["url"] + page_path),
        "og_image": esc(site["url"] + og_image if is_local(og_image) else og_image),
        "og_image_size": ('<meta property="og:image:width" content="%d">\n<meta property="og:image:height" content="%d">\n' % og_size) if og_size else "",
        "og_image_alt": esc(meta.get("og_image_alt") or site["og_image_alt"]),
        "nav_links": render_nav(site, meta.get("nav")),
        "main_class": esc(meta.get("main_class") or "page-container"),
        "content": content.rstrip("\n"),
        "footer_links": render_footer_links(site),
        "year": site["year"],
        "secret": esc(meta.get("secret", "")),
        "script": esc(meta.get("script") or "about.js"),
    }
    page = fill(layout, values, "src/layout.html")
    page = relink(add_image_sizes(page), root)
    path = ROOT / output
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(page)
    print("built", output)
    return page_path


def build():
    site = load_site()
    projects = load_projects()
    logos, logos_duration = render_logos(load_logos())
    _, layout = read_template(SRC / "layout.html")
    shared = {
        "age": esc(site["age"]), "year": site["year"],
        "projects": render_cards(projects), "project_count": len(projects),
        "logos": logos, "logos_duration": logos_duration,
    }
    urls = []

    for source in sorted((SRC / "pages").glob("*.html")):
        meta, body = read_template(source)
        rel = source.relative_to(ROOT).as_posix()
        for key in ("output", "title"):
            if not meta.get(key):
                raise BuildError("%s: front matter needs `%s:`" % (rel, key))
        urls.append(render_page(site, layout, meta, fill(body, shared, rel), meta["output"], rel))

    # Project pages, and removing pages of projects that were deleted, archived or set to draft
    meta, body = read_template(SRC / "project.html")
    keep = {p["Slug"] for p in projects}
    if WORK.exists():
        for d in sorted(WORK.iterdir()):
            page = d / "index.html"
            if d.is_dir() and d.name not in keep and page.exists() and MARKER in page.read_text(encoding="utf-8"):
                shutil.rmtree(d)
                print("removed", d.relative_to(ROOT).as_posix())
    for p in projects:
        og = "assets/img/work/%s/og.jpg" % p["Slug"]
        page_meta = dict(meta, title=p["Heading"] + " – " + site["name"], og_title=p["Heading"], description=p["description"],
                         og_image_alt=p["Heading"], **({"og_image": og} if (ROOT / og).exists() else {}))
        content = fill(body, project_values(p), "src/project.html")
        urls.append(render_page(site, layout, page_meta, content, "work/%s/index.html" % p["Slug"], "content/projects.csv"))

    write_sitemap(site, urls)


def write_sitemap(site, paths):
    """sitemap.xml: home first, then the other pages, then projects."""
    paths = sorted(paths, key=lambda p: (p != "", p.startswith("work/"), paths.index(p)))
    body = "\n".join("  <url><loc>%s</loc></url>" % esc(site["url"] + p) for p in paths)
    with open(ROOT / "sitemap.xml", "w", encoding="utf-8", newline="\n") as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n'
                '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n%s\n</urlset>\n' % body)
    print("built sitemap.xml")


def main():
    try:
        build()
    except BuildError as e:
        raise SystemExit("error: %s" % e)


if __name__ == "__main__":
    main()
